### ISSUE TITLE
Images get lost after changing the template course category

### ISSUE THREAD

**Issue by mudrd8mz** [moodleworkplace/moodle-tool_certificate#52]
Somehow, images got completely lost from my template and I had to upload them again into element editors. I also had to delete all issued certificates because there was no obvious way to re-generate the PDF once they were issued.

I was trying to debug what was going on and I noticed that both files are now present in the `mdl_files` table - but each one with different `contextid`. That gave me a hint and I realised what had happened and how to reproduce it.

### Steps to reproduce ###

1. Create a new template. Leave the "Course category" field "None".
2. Add an image element. Uploaded image gets saved on the system context level.
3. Edit the template and change the "Course category" to some other value.
4. Preview or edit the template - the image is gone now because the tool tries to find it in the course category context.

**Comment by marinaglancy** [comment]
Thanks David! This has been fixed in the commits
https://github.com/moodleworkplace/moodle-tool_certificate/commit/8d99782d8a59e92b7841b073f328db263a4b17ad
and 
https://github.com/moodleworkplace/moodle-tool_certificate/commit/201f89a0ea0fb012eeea1a73b47a240b04815f3f

I'm closing this issue and I'm also disabling the "Issues" feature in github for this component. All issues should be reported in moodle tracker:

project CONTRIB, component "Set: Course certificate". The "Bug tracker" link on the plugin page is updated
https://tracker.moodle.org/issues/?jql=project%20%3D%20CONTRIB%20AND%20component%20%3D%20%22Set%3A%20Course%20certificate%22
